mongodb_uri: "mongodb+srv://{{ mongodb_username }}:{{ mongodb_password }}@cluster0.q0bvqux.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

mongodb_database: "TodoDB"
mongodb_username: "todo-app"
mongodb_password: "admin"

db_password: "{{ mongodb_password }}"

gmail_username: "zannurita@gmail.com"
gmail_password: "vwhm iimb grsj cthh"
jwt_secret: "8917410b897d631ab71037d594a55db9b26cac7744d0dab17b4f5149c4098a3c"

 


