# - name: Ensure git is installed
#   package:
#     name: git
#     state: present

- name: Install dependencies
  package:
      name:
        - curl
        - git
        - bash
      state: present

- name: Clone application repository
  git:
    repo: "https://github.com/senzxita/Todo-app.git"
    dest: /var/www/Todo-app
    version: dev
    force: yes

# - name: Remove default NGINX HTML content
#   file:
#     path: /usr/share/nginx/html
#     state: absent

# - name: Install Node.js and npm
#   package:
#     name: nodejs
#     state: present
#   become: true


# - name: Install NVM
#   become: false
#   shell: |
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
#   args:
#     creates: /home/{{ ansible_user_id }}/.nvm/nvm.sh

# - name: Load NVM environment
#   shell: |
#     export NVM_DIR="$HOME/.nvm"
#     [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
#     nvm install 20
#     nvm alias default 20
#   args:
#     executable: /bin/bash
#   become: false

# - name: Verify Node.js version
#   shell: |
#     export NVM_DIR="$HOME/.nvm"
#     [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
#     node -v
#   args:
#     executable: /bin/bash
#   register: node_version
#   become: false

# - name: Display Node.js version
#   debug:
#     msg: "Installed Node.js version: {{ node_version.stdout }}"


#######################
# 


- name: Install NVM, Node.js LTS, and frontend dependencies, then build the app
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

    export NVM_DIR="$HOME/.nvm"
    source $NVM_DIR/nvm.sh

    nvm install --lts
    nvm use --lts
    nvm alias default lts/*

    cd /var/www/Todo-app/frontend
    npm install
    npm run build
  args:
    executable: /bin/bash



- name: Deploy frontend build to NGINX web root
  copy:
    src: /var/www/Todo-app/frontend/build/
    dest: /usr/share/nginx/html/
    owner: nginx
    group: nginx
    mode: '0755'
  notify: restart nginx

- name: Ensure app config directory exists
  file:
    path: /etc/myapp
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure application with MongoDB settings
  template:
    src: app_config.j2
    dest: /etc/myapp/config.yml
    mode: '0644'

- name: Create backend .env file
  template:
    src: .env.j2
    dest: /var/www/Todo-app/backend/.env
    mode: '0600'

###################
# 

- name: Install NVM, Node.js LTS, backend dependencies, and PM2
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

    export NVM_DIR="$HOME/.nvm"
    source $NVM_DIR/nvm.sh

    nvm install --lts
    nvm use --lts
    nvm alias default lts/*

    cd /var/www/Todo-app/backend
    npm install

    npm install -g pm2
  args:
    executable: /bin/bash





# - name: Ensure git is installed
#   package:
#     name: git
#     state: present

# - name: Clone application repository
#   git:
#     repo: "https://github.com/senzxita/Todo-app.git" 
#     dest: /var/www/Todo-app
#     version: dev

# - name: Remove default NGINX HTML content
#   file:
#     path: /usr/share/nginx/html
#     state: absent

# - name: Deploy application content to NGINX web root
#   copy:
#     src: /Todo-app
#     dest: /usr/share/nginx/html/
#     owner: nginx
#     group: nginx
#     mode: '0755'
#   notify: restart nginx


# - name: Configure application with MongoDB settings
#   template:
#     src: app_config.j2
#     dest: /etc/myapp/config.yml

# - name: Create backend .env file
#   template:
#     src: .env.j2
#     dest: /var/www/Todo-app/backend/.env
#     mode: '0600'

# - name: Install backend dependencies
#   shell: npm install
#   args:
#     chdir: /var/www/Todo-app/backend

# - name: Start backend with Nodemon
#   shell: nodemon server
#   args:
#     chdir: /var/www/Todo-app/backend

# - name: Install frontend dependencies
#   shell: npm install
#   args:
#     chdir: /var/www/Todo-app/frontend

# - name: Start frontend with npm
#   shell: npm start
#   args:
#     chdir: /var/www/Todo-app/frontend