- name: Apply security updates on CentOS 8 and above
  hosts: dev
  become: yes
  roles:
    - security

- name: Configure NGINX
  hosts: dev
  become: yes
  roles:
    - nginx


- name: Configure TODO app
  hosts: dev
  become: yes
  roles:
    - app